app = "baserow-app"

[build]
  dockerfile = "Dockerfile"

[[services]]
  name = "web"
  internal_port = 80
  cmd = "gunicorn baserow.config.wsgi:application --bind 0.0.0.0:80"
  protocol = "http"

[env]
  DJANGO_SETTINGS_MODULE = "baserow.config.settings.production"
